### ISSUE TITLE
Submit and Reset buttons do not get ENV classes

### ISSUE THREAD

**Issue by maprules1000** [martndemus/ember-form-for#100]
Right now the classes for reset and submit don't get pulled from the ENV file. It looks like `addon/components/form-controls/button.js` gets the button class, but `reset` and `submit` just extend the `button` component without adding their own classes.

Should `init()` be called on both the sub-buttons, or should that be avoided and done a different way?

**Comment by martndemus** [comment]
Fixed by #114
