### ISSUE TITLE
Conditional fields with inline changeset declaration?

### ISSUE THREAD

**Issue by maprules1000** [martndemus/ember-form-for#115]
If I've got 
`{{#form-for (changeset object) submit=.... as |o|}}` 
  &nbsp;&nbsp;&nbsp;&nbsp;`{{o.checkbox-field "isAnimal"}}`
is it possible to then somehow reference the object and say:
  &nbsp;&nbsp;&nbsp;&nbsp;`{{#if o.object.isAnimal}}` ... `{{/if}}`?

**Comment by lcpriest** [comment]
I'm not sure that is possible.

You could predefine the change set in your component javascript file and then use
```
{{#form-for objectChangeset submit=.... as |o|}}
    {{o.checkbox-field "isAnimal"}}
```

and `{{#if objectChangeset.isAnimal}} ... {{/if}}`
