### ISSUE TITLE
Add hidden class to the labels for hidden fields.

### ISSUE THREAD

**Issue by jemware** [martndemus/ember-form-for#125]
I need to use hidden fields in my app, but hidden fields still have visible labels. As you explained in #34, I understand the need to always render labels for accessibility reasons. That said, I think it would be useful to add a class (maybe configurable) to labels associated with hidden fields, so we can hide the labels with CSS.

**Comment by lcpriest** [comment]
You can add `labelClasses='hidden'` or whatever your class for hiding labels is to an input.
