### ISSUE TITLE
select-field doesn't set set optionValuePath on change

### ISSUE THREAD

**Issue by ivanvanderbyl** [martndemus/ember-form-for#133]
When using `optionValuePath` with `select-field` i.e.

```hbs
{{f.select-field "tool"
  label="Tool"
  options=tools
  optionLabelPath="name"
  optionValuePath="id"
  prompt="Select tool..."
}}
```

It sets the actual object to `tool`, not the `id` from the selected option, as desired from `option[value]`.

Version: `alpha.13`

**Comment by martndemus** [comment]
You are likely looking for `optionTargetPath`. See towards the bottom of the [Working with objects instead of strings](https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-select.md#working-with-objects-instead-of-strings) part of ember-one-way-controls documentation.

**Comment by ivanvanderbyl** [comment]
Thanks for pointing that out. What's the use case for having both `optionTargetPath` and `optionValuePath`?

**Comment by martndemus** [comment]
`optionValuePath` is for when you want to select the whole object. It uses `optionValuePath` to compare objects for equality to check which one is selected.

**Comment by martndemus** [comment]
I believe this issue is resolved now.
