### ISSUE TITLE
2.0.0-alpha.13:`select-field` sending obj rather than obj.value on update

### ISSUE THREAD

**Issue by kevlarr** [martndemus/ember-form-for#136]
Say I have the following array on a component...

```
characters: [
  { ship: 'Serenity', name: 'Malcom Reynolds', value: 'reynolds' },
  { ship: 'Serenity', name: 'Jayne Cobb', value: 'cobber' },
  { ship: 'Nostromo', name: 'Ellen Ripley', value: 'rippers' },
  { ship: 'Millennium Falcon', name: 'Han Solo', value: 'han_solo' },
  ...
]
```

... and I'm using it in a form like so.

```
{{#form-for myFavoriteThings as |f|}}
  {{f.select-field "character" characters
    groupLabelPath="ship"
    optionLabelPath="name"
    optionValuePath="value"
  }}
{{/form-for}}
```

This correctly (and awesomely!) renders my `<select>` input complete with option groups of characters arranged by their respective ship.

```
<select>
  <optgroup label="Serenity">
          <option value="reynolds">Malcom Reynolds</option>
          ...
  </optgroup>
  ...
</select>
```

The label displayed for each option is correct, as is the value assigned to the option.

When I click an option, however, an **entire Ember object** (generated somewhere in `fields-for`) is passed to the update function, rather than the specific value assigned to the `<option>` extracted by `optionValuePath`.

Unless I override this with my own update function to conditionally check if the value argument is an object, it sets `myFavoriteThings` to...
```
{
  character: {
    ship: 'Serenity',
    name: 'Malcolm Reynolds',
    value: 'reynolds'
  }
}
```
... rather than...

```
{
  character: 'reynolds'
}
```

... as it *should* be set to with `<option value="reynolds">`

**Comment by kevlarr** [comment]
Also, if I provide a custom `update` method to the `form-for` where I extract and set the object value itself, this has a strange effect that if I select something from the dropdown it sets on the object but it doesn't change the "selected" value in the dropdown. Selecting an option (the same or a different one) a second time **will** update the selected value.

**Comment by martndemus** [comment]
Please read: https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-select.md#working-with-objects-instead-of-strings

**Comment by kevlarr** [comment]
@martndemus Thank you! Apologies for raising this as an issue
