### ISSUE TITLE
Transitioning after a save raises an error

### ISSUE THREAD

**Issue by mwpastore** [martndemus/ember-form-for#139]
```
Ember      : 2.11.0-beta.2
Ember Data : 2.11.0-beta.1
jQuery     : 3.1.1
```

Calling `Route#transitionTo()` in the save action of a form raises the following error:

```
Uncaught TypeError: Cannot read property 'focus' of undefined
    at form-for.js:53
    at invoke (ember.debug.js:336)
    at Queue.flush (ember.debug.js:404)
    at DeferredActionQueues.flush (ember.debug.js:528)
    at Backburner.end (ember.debug.js:598)
    at Backburner.run (ember.debug.js:721)
    at Backburner.join (ember.debug.js:743)
    at Function.run.join (ember.debug.js:21614)
    at Class.hash.success (rest.js:954)
    at fire (jquery.js:3305)
```

The form saves and the transition occurs, but I'd like to understand if there's a better way to do this, or if this is a bug we can fix somehow.

**Comment by Geokoumpa** [comment]
From what I've seen, this only occurs if the action's name is `submit`. Changing it to something else stopped the form from calling `handleErrors` inside form-for.js.

**Comment by kevlarr** [comment]
I ran into this too - how did you pass a `save` action into the form? It seems like it only calls `submit`.

I wound up overriding the component with one that didn't do the `handleErrors` bit, because we didn't want the form to be focused like that.

**Comment by Geokoumpa** [comment]
@kevlarr That was as easy as adding `submit=(action 'save')` to the form component arguments, as seen here https://github.com/martndemus/ember-form-for#syntax

I also wish the addon was a bit more customizable, I'll have to create some custom controls just for styling purposes, but I believe eventually it will become the go-to addon for ember form creation.

**Comment by mwpastore** [comment]
Yeah, I'm using a route-action named `signup` and it's raising the same error, so I don't think that's the issue, or at least not the whole issue.

**Comment by elgordino** [comment]
I am getting this same exception, but when saving the data I am altering the template to remove the form, rather than performing a route transition, my form is defined like this:

`{{#form-for (changeset model UserValidations) submit=(action "save")  as |f|}}`

I am using ember 2.9.1. I'm also very new to ember so quite possibly just getting something wrong!

**Comment by elgordino** [comment]
I have this working for me, but not entirely sure if I'm masking a potential future issue.

I noticed that the code in handleErrrors was still scheduling an 'afterRender' event even if 'errors' is an empty array. Presumably this is not intended? So I added a check for array length.

Additionally I changed the afterRender to check that this.$() is still defined before calling focus on it, as this.$() being undefined is what was causing the exception to be thrown.

https://github.com/lineupninja/ember-form-for/commit/484cf51b78972281d9d37d33376aac438e0cb59c

Hope this helps. I can submit as a PR if that's appropriate.

**Comment by kevlarr** [comment]
@Geokoumpa Ah I thought you meant passing an action to the form-for's save.. Yeah, I passed a component action to `submit`, but that didn't change anything for me because it still calls `this.handleErrors` in both conditions of the `if/else` after that

**Comment by oskarrough** [comment]
Also having this bug. As a workaround, I wrapped the `transitionTo` in the run loop.

```js
Ember.run.schedule('afterRender', () => {
  this.transitionTo('posts.post', model);
})
```

**Comment by marxsk** [comment]
After merging #147, the included tests are working without modifying form-for.js

Thanks, for the participation and we will try to be faster next time.
