### ISSUE TITLE
[doc] update method

### ISSUE THREAD

**Issue by marxsk** [martndemus/ember-form-for#149]
It would be nice, to add an example for 'update' method because you cannot just call parent's update action from your code. Something as simple as 

    onUpdate(obj, fieldName, fieldValue): {
      Ember.set(obj, fieldName, fieldValue);
    }

so users don't have to find it in source code.

**Comment by lcpriest** [comment]
Want to make this a pull request?

**Comment by marxsk** [comment]
@lcpriest I would prefer not. My English is far from writing texts for others :)

**Comment by lcpriest** [comment]
Wait - is that not covered by this? 
https://github.com/martndemus/ember-form-for#update

What does the onUpdate method do that the update method doesn't?

**Comment by marxsk** [comment]
I miss the last sentence. It is already there.
