### ISSUE TITLE
Input styles

### ISSUE THREAD

**Issue by samsebastian** [martndemus/ember-form-for#15]
Is there currently a way to add styles like ``form-control`` etc to the inputs?

**Comment by martndemus** [comment]
Not yet, will come to that soon. I will also accept a PR doing that.

**Comment by martndemus** [comment]
@samsebastian I added a few basic styling things in 1.3.0, will expand on that and make it configurable later on.

Each field will now get the `.form-control` class and `.form-control--errors` class when invalid.

**Comment by martndemus** [comment]
Closed by #30
