### ISSUE TITLE
Disable submit button on validation errors

### ISSUE THREAD

**Issue by hugoruscitti** [martndemus/ember-form-for#162]
Hi !, this addon is awesome, but i'm font find any example or documentation about disable the submit button on validation error. 

Is possible ? maybe there are any way to get the model whitin block content in template? or there are any simple way?

thanks!

**Comment by hugoruscitti** [comment]
we end using something like this:

```
{{#with (changeset user validations) as |data|}}

  {{#form-for data
    submit=(route-action 'submit')
    as |f|}}

    <p>is valid: {{data.isValid}}</p>

  {{/form-for}}

{{/with}}
```

**Comment by lcpriest** [comment]
Given that validations are handled outside of this add-on, I think you would have to resort to applying it to each submit button.

`{{f.submit 'Submit form' disabled=(not data.isValid)}}` or something should work.
