### ISSUE TITLE
Bug: Error classes not calculated on route.refresh

### ISSUE THREAD

**Issue by knownasilya** [martndemus/ember-form-for#166]
Since the components don't tear down and rerender, the following doesn't get called: https://github.com/martndemus/ember-form-for/blob/master/addon/components/form-field.js#L64 and `form-errors` component doesn't have the `errorClasses` array.

**Comment by marxsk** [comment]
@knownasilya I have exactly same problem. My work-around is to change form-field.hbs to not use errorClasses but hard-code the values. I'm still not sure why the content of lost. Do you have any idea or solution?

**Comment by marxsk** [comment]
This have to be patched in the code. I will prepare PR later. 

Full description: https://stackoverflow.com/questions/49013620/component-life-cycle

**Comment by marxsk** [comment]
Fixed in #214
