### ISSUE TITLE
Date-time field

### ISSUE THREAD

**Issue by lcpriest** [martndemus/ember-form-for#174]
I don't think it has worked since ember-one-way-controls were implemented.

I've opened an issue there too: https://github.com/DockYard/ember-one-way-controls/issues/154

"Assertion Failed: The component helper cannot be used without a valid component name. You used "one-way-datetime" via (component "one-way-datetime")"

**Comment by marxsk** [comment]
As ember-one-way-controls are no longer in development, I'm removing support for this field. 

PR# https://github.com/martndemus/ember-form-for/pull/211
