### ISSUE TITLE
How to do nested propertyName?

### ISSUE THREAD

**Issue by rwwagner90** [martndemus/ember-form-for#178]
I'm trying to do some nested sections, for adding education and employment, and I am not sure what to put for propertyName?

```hbs
{{#each changeset.jobs as |job index|}}
   {{f.text-field
     label="Employer Name"
     placeholder="Employer Name"
     required=true
     propertyName="jobs.index.employerName}}
{{/each}}
```

Since I need to access each index in the array, I am unsure how to proceed. The example above has some pseudocode of what I am looking for.

**Comment by knownasilya** [comment]
See https://github.com/martndemus/ember-form-for#quickstart-example

```hbs
{{#fields-for changeset.jobs.index as |fa|}}
    {{fa.text-field "employerName"}}
  {{/fields-for}}
```

**Comment by rwwagner90** [comment]
Thanks @knownasilya somehow my brain didn't connect that with using `each` and having multiple of the same thing, but just with the example where it is simply fields of a single address. Might be helpful to list explicitly in the docs.

**Comment by joshuataylor** [comment]
When doing it this way, one f the issues is that it renders quite slowly if you have a large embedded form. I have 9 fields with 28 embedded entries, and it takes about 1.5 seconds for the page to load.

**Comment by knownasilya** [comment]
I wouldn't be too sure it's related to this. Ember is quite good at rendering many components, much more than what you describe.

**Comment by joshuataylor** [comment]
@knownasilya I'm rendering 285 fields, the form takes 1,566.05ms to render.
