### ISSUE TITLE
How can I remove the wrapper div or change its type from div to any tag else?

### ISSUE THREAD

**Issue by NouranMahmoud** [martndemus/ember-form-for#180]
I am using bulma.io and for using its style classes for selectbox it requires the following code.
```
<div class="field">
  <label class="label">Subject</label>
  <p class="control">
    <span class="select">
      <select>
        <option>Select dropdown</option>
        <option>With options</option>
      </select>
    </span>
  </p>
</div>
```
which requires a span instead of div for wrapping the (label and select tag).

I've tried to use `tagName="span"` but the generated code was like that [link](https://ibb.co/djBZvk)

here is my code

```
           <div class="field">
              <p class="control">
                {{f.select-field "countries"
                  countries
                  optionValuePath="value"
                  optionLabelPath="text"
                  labelClasses="label"
                  label="Location"
                  required=true
                  tagName="span"
                }}
              </p>
            </div>
```

which generated a span wrapping the div .. not converting the div to span
`<span><div><label><select></div></span>`

**Comment by lcpriest** [comment]
I don't think that structure is possible without overriding the select-field template file in your own app.

https://github.com/martndemus/ember-form-for/blob/master/addon/templates/components/form-fields/select-field.hbs
