### ISSUE TITLE
Setting default of radio-field

### ISSUE THREAD

**Issue by jakeboyles** [martndemus/ember-form-for#189]
How does one go about setting the default for a radio field? Can't find it anywhere in the docs.

**Comment by lcpriest** [comment]
@jakeboyles any reason why you don't set the default value on the formObject?

**Comment by mhluska** [comment]
It's not clear how to do this if `formObject` is a typical record and handles non-humanized values. For example, `drivers_license` vs `Driver's License`. The record will likely hold `drivers_license` so we pass formatted values like `Driver's License` to `{{f.radio-group}}` via the `options` key instead. How can a default be set in this scenario?

**Comment by marxsk** [comment]
@mhluska 
I will use a computed property for this purpose which will do humanization. And any attempt to set value from options will be de-humanized in the setter. 

The other way might be to re-define (or create a new one) element for radio-group so it can handle labels for every key.
