### ISSUE TITLE
Issue with fastboot and i18n initializer

### ISSUE THREAD

**Issue by PrinceCornNM** [martndemus/ember-form-for#190]
When I load a ember-form-for component in fastboot I get: `TypeError: Cannot read property 'lookup' of undefined` in `/initializers/ember-form-for-i18n.js`. I think its because the container might not be available.

**Comment by marxsk** [comment]
@PrinceCornNM It looks like it is the same issue as with ember-engines. Can you please take a look at relevant PR ?

**Comment by lougreenwood** [comment]
I've just hit the same issue - attempted to use the add-on for the first time and seeing the same error:

`TypeError: Cannot read property 'lookup' of undefined`

**Comment by mhluska** [comment]
Same issue here. Was this ever resolved?

**Comment by proteamer** [comment]
I've faced with the same issue when run `ember test`.

**Comment by marxsk** [comment]
@proteamer thanks for this test. I'm back from (really long) holidays, so I will fix that soon.

**Comment by marxsk** [comment]
Fixed in #227, if not feel free to reopen this bug.

**Comment by michaelrkn** [comment]
I'm running into this issue with Fastboot:

```
$ ember -v
ember-cli: 3.7.0
node: 8.3.0
os: darwin x64
$ ember new testing
...
$ cd testing/
$ ember install ember-form-for
$ ember install ember-cli-fastboot
$ ember generate component hello-world
$ ember s
[visit http://localhost:4200/]
TypeError: Cannot read property 'lookup' of undefined
```

**Comment by marxsk** [comment]
@michaelrkn Which version of package do you have?

**Comment by michaelrkn** [comment]
I installed the latest - package.lock says 2.0.0.

**Comment by marxsk** [comment]
@michaelrkn can you please test the repository directly? This bug should be already fixed, if it will work, then I will create a new release next week

**Comment by michaelrkn** [comment]
Yup, that seems to have fixed it. Didn't realize it had been so long since a release!

**Comment by marxsk** [comment]
2.0.1 published
