### ISSUE TITLE
Cannot reset submit button on response catch

### ISSUE THREAD

**Issue by npendery** [martndemus/ember-form-for#194]
I am trying to reset the submit button after an error is caught from the submit request but dont see a good way of doing this...

**Comment by lcpriest** [comment]
@npendery what do you mean by reset? It usually only stays grayed out if the error is not caught.

Can you share some code?
Also, which version of the package are you using?

**Comment by npendery** [comment]
By reset, I mean to go back to the clickable format with the original text. My save action is:
```
save(params) {
      let store = get(this, 'store');
      let newUser = store.createRecord('user', params);
      newUser
        .save()
        .then((user) => { this.transitionToOnboarding(user); })
        .catch(() => { get(this, 'notify').error("Could not create user"); });
```

**Comment by lcpriest** [comment]
@npendery if you put a debugger in your catch, does it get processed?

**Comment by marxsk** [comment]
@npendery have you tried to return a promise? When the promise is resolved, the submit button is available again (Ember.RSVP.resolve() should be enough for tests)

**Comment by marxsk** [comment]
not enough information to reproduce, feel free to reopen
