### ISSUE TITLE
hidden-field label still shows

### ISSUE THREAD

**Issue by npendery** [martndemus/ember-form-for#195]
`hidden-label` fields still show the label of the field. cannot even change the label to be blank as it reverts to the original label

**Comment by lcpriest** [comment]
Hi @npendery!

Check out https://github.com/martndemus/ember-form-for/issues/125.

We don't hide labels (though we allow them to be hidden). This is because screen-readers need to read a label of an input, even if you want to hide it.

**Comment by npendery** [comment]
Ahh, thanks @lcpriest!!
