### ISSUE TITLE
You modified ... twice on ...

### ISSUE THREAD

**Issue by marxsk** [martndemus/ember-form-for#196]
Environment:  Ember 2.15.3

Reproducer:
```
  model() {
    let foo = Ember.Object.create();
    foo.set('order', 'Second');
    foo.set('freetext', 'Foo Bar');

    return Ember.RSVP.hash({
      foo: foo,
    });

{{#form-for model.foo as |f|}}
  {{f.select-field 'order' 'First Second'}}
{{/form-for}}
```

After clicking on select box and changing item:

"Assertion Failed: You modified "promptIsSelectable" twice on <reproducer1@component:form-fields/select-field::ember382> in a single render. It was rendered in "component:one-way-select" and modified in "component:one-way-select". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details."

I'm almost sure that the problem is in upgrading Ember but I did not found a way how to fix it yet.

**Comment by marxsk** [comment]
The second modification of promptIsSelectable (and options) is in didReceiveAttrs() in ./ember-one-way-controls/addon/components/one-way-select.js

**Comment by marxsk** [comment]
Closing the issue because the bug was tracked down to ember-one-way-controls where it should be fixed. https://github.com/DockYard/ember-one-way-controls/pull/176

**Comment by deepflame** [comment]
:( unfortunately this PR was not merged in...
Please see here: https://github.com/DockYard/ember-one-way-controls/blob/v3.1.0/addon/components/one-way-select.js#L67
