### ISSUE TITLE
Upgrade ember-one-way-controls to prevent double rendering in select-field

### ISSUE THREAD

**Issue by marxsk** [martndemus/ember-form-for#197]
relevant PR for one-way-controls is https://github.com/DockYard/ember-one-way-controls/pull/176

unfortunately, it is not in upstream yet. You have to use https://github.com/sandydoo/ember-one-way-controls.git#fix-modified-twice-render-assertion instead.

**Comment by deepflame** [comment]
@marxsk unfortunately the related PR was never merged in. So the error still persists...

**Comment by marxsk** [comment]
@deepflame I will replace one-way-controls with my fork that will contain fixes. I'm already using forked version because of that.

**Comment by marxsk** [comment]
@deepflame Can you please test PR #212 ?

It works for me but I would like to be sure.

**Comment by deepflame** [comment]
Hey @marxsk , sorry for not getting back to you earlier, got swamped here. Hope everything is good... (and thanks for the fix!)

**Comment by AmboMaya** [comment]
Seems like this double render issue may be why our `f.select-field` component is crashing Safari.

As an interim solution we are using a different select field for now.

**Comment by marxsk** [comment]
@AmboMaya are you using the github version or release?

**Comment by AmboMaya** [comment]
@marxsk i'm actually using ember-basic-dropdown release v2.0.4. I tried github forked version and it's still crashing.
