### ISSUE TITLE
Please upgrade dependencies that include ember-cli-version-checker

### ISSUE THREAD

**Issue by thomblake** [martndemus/ember-form-for#213]
ember-form-for directly depends on outdated ember-cli-babel and ember-cli-htmlbars, which depend on outdated ember-cli-version-checker and leads to this deprecation warning: https://github.com/ember-cli/ember-cli-version-checker/issues/48 .

Also several other dependencies should be upgraded to get the version that uses updated dependencies for the same reason:

 - ember-async-button (not available yet - issue: https://github.com/DockYard/ember-async-button/issues/102 )
 - ember-invoke-action (can be upgraded to 1.5.0 )
 - ember-one-way-controls (can be upgraded to 3.1.0 )

latest `npm ls ember-cli-version-checker` tree:

```
├─┬ ember-form-for@2.0.0-alpha.17
│ ├─┬ ember-async-button@1.0.2
│ │ ├─┬ ember-cli-babel@5.2.4
│ │ │ └── ember-cli-version-checker@1.3.1  deduped
│ │ └─┬ ember-cli-htmlbars@1.3.4
│ │   └── ember-cli-version-checker@1.3.1  deduped
│ ├─┬ ember-cli-babel@5.2.4
│ │ └── ember-cli-version-checker@1.3.1  deduped
│ ├─┬ ember-cli-htmlbars@1.3.4
│ │ └── ember-cli-version-checker@1.3.1  deduped
│ ├─┬ ember-invoke-action@1.4.0
│ │ └─┬ ember-cli-babel@5.2.4
│ │   └── ember-cli-version-checker@1.3.1  deduped
│ └─┬ ember-one-way-controls@2.0.1
│   └─┬ ember-get-helper@1.1.0
│     ├─┬ ember-cli-babel@5.2.4
│     │ └── ember-cli-version-checker@1.3.1  deduped
│     └── ember-cli-version-checker@1.3.1  deduped
```

**Comment by marxsk** [comment]
Okay, let's wait for ember-async-button.

**Comment by thomblake** [comment]
ember-async button is now deprecated and so not likely to be fixed. They recommend using a pattern instead. https://github.com/thomblake/ember-async-button#how-can-i-do-this-myself

**Comment by marxsk** [comment]
@thomblake thanks for info. I will try to replace it with proposed pattern

**Comment by marxsk** [comment]
@thomblake Please, take a look at #217 . It should solve the ember-async-button problem. If it will work good enough, I will upgrade the rest next week and publish next pre-release.

**Comment by marxsk** [comment]
#221 was merged in the upstream. It will be part of next beta.
