### ISSUE TITLE
`reset` option of submit component is broken in master

### ISSUE THREAD

**Issue by stephankaag** [martndemus/ember-form-for#223]
This feature does no longer work: https://github.com/DockYard/ember-async-button#reset

**Comment by marxsk** [comment]
@stephankaag Thanks for reporting, I will fix it before next beta.

**Comment by marxsk** [comment]
Please, take a look at #224 - I hope that it works as you expected.

**Comment by stephankaag** [comment]
Works for me!

**Comment by stephankaag** [comment]
Would be nice if the button component also supports this

**Comment by marxsk** [comment]
@stephankaag Do you use submit & button in different situation? Cannot it be handled by single instance?
