### ISSUE TITLE
DEPRECATION: 'propertyDidChange' is deprecated in favor of 'notifyPropertyChange'. It is safe to change this call to 'notifyPropertyChange'

### ISSUE THREAD

**Issue by mhluska** [martndemus/ember-form-for#234]
A deprecation error after upgrading to ember-cli 2.5.1

**Comment by bitwolfe** [comment]
This needs a bump. `propertyDidUpdate` has now been removed from Ember 3.7 onwards.

**Comment by bitwolfe** [comment]
I have fixed this in https://github.com/martndemus/ember-form-for/pull/237 to make Ember 3.7+ compatible.

**Comment by marxsk** [comment]
Merged in the upstream.
