### ISSUE TITLE
You modified (mut required) twice in a single render

### ISSUE THREAD

**Issue by safo6m** [martndemus/ember-form-for#33]
Cite from console:

> DEPRECATION: You modified (mut required) twice in a single render. This was unreliable in Ember 1.x and will be removed in Ember 3.0 [deprecation id: ember-views.render-double-modify]

This pops up after entering the first character into input field.

Bug reproduced with a clean ember application using "Quickstart example" from ember-form-for Readme.

Versions:
browser: chrome 49
ember-form-for: 1.3.0

**Comment by seifsallam** [comment]
Same problem here

**Comment by martndemus** [comment]
Fix released in 1.4.1
