### ISSUE TITLE
What's the API to not render a label?

### ISSUE THREAD

**Issue by lcpriest** [martndemus/ember-form-for#34]
```
  {{f.email-field 'identification'
          autofocus="autofocus"
          name="email"
          label=false
          placeholder=(t 'models.users.placeholders.email')}}
```

Doesn't seem to work

**Comment by martndemus** [comment]
There isn't, you should ALWAYS have a label.
You can however add a class to the label using for example `labelClasses="hidden"`.

See [this accessibility page](http://www.w3.org/WAI/tutorials/forms/labels/) for the why.

**Comment by lcpriest** [comment]
Thanks!
