### ISSUE TITLE
Custom classes per submit?

### ISSUE THREAD

**Issue by lcpriest** [martndemus/ember-form-for#37]
Is there any way to do something along the lines of:
`{{f.submit fieldClasses="el-button--primary el-button--block el-button--footer"}}`

For *one* submit button? I can only see the environment config.

**Comment by martndemus** [comment]
Just:
```hbs
{{f.submit class="el-button--primary el-button--block el-button--footer"}}
```
😄

**Comment by lcpriest** [comment]
Ah, simple stuff!
