### ISSUE TITLE
Haystack and needle don't match

### ISSUE THREAD

**Issue by musaffa** [martndemus/ember-form-for#42]
When trying to implement belongs field with some selection options, [this line](https://github.com/martndemus/ember-form-for/blob/master/addon/helpers/contains.js#L9) of code is executed and they never match as haystack and needle are two different ember objects. A simple remedy is to match the id attributes like this:

```Javascript
haystack.get('id') === needle.get('id');
```

Current tests use POJO objects which don't correspond to the real world complexity of ember objects. That's why the tests pass but the helper fails in the real application environment.

**Comment by martndemus** [comment]
If this is still an issue, then please open an issue with ember-one-way-controls.
