### ISSUE TITLE
Etiquette on running a fork

### ISSUE THREAD

**Issue by lcpriest** [martndemus/ember-form-for#43]
Hi team - I love this project! I have a fork running that I will auto-lookup translations for inputs (I doubt it could get merged back in, it's a bit too opinionated - If I am wrong, let me know and I'll open a PR).

Is there anything you want me to put in the README or LICENSE files (or others) I should be aware of? I won't be putting it on npm, just in a public repo [here](https://github.com/advocately/ember-form-for-i18n). 

Should I rename it to prevent google indexing it and confusing people?

**Comment by martndemus** [comment]
Hi @lcpriest,

I think the translation idea is great, I will take a look and see how I can incorporate your thing into ember-for-for!
