### ISSUE TITLE
Select field question

### ISSUE THREAD

**Issue by lcpriest** [martndemus/ember-form-for#53]
This form lets a customer dictate select a column from a list of columns.
```
    {{f.select-field 'subscriptionField'
                     model.accountFields
                     optionValuePath='id'
                     optionLabelPath='value'}}
```
`model.accountFields` returns an array of objects like this:
```
[
  {id: "CustomerPriority__c", value: "Customer Priority"},
  {id: "SLA__c", value: "SLA"},
  {id: "Active__c", value: "Active"}
]
```

This issue I am experiencing is that on change, the model.subscriptionField is being set as the entire object, rather than just the `Ember.get(model, 'optionValuePath')`. Any tips here?

**Comment by phikes** [comment]
I see this, too!

**Comment by phikes** [comment]
@martndemus Are we doing something wrong?

**Comment by martndemus** [comment]
This is intended, `optionValuePath` and `optionLabelPath` are for display purposes

**Comment by phikes** [comment]
So for the above example the model's `subscriptionField` would be `{id: "CustomerPriority__c", value: "Customer Priority"}` but I want it to be `CustomerPriority__c`. How can I get the behaviour I want?

Also if it is for displaying purposes only, then why is the model's field set to the whole object, rather then it's `id` field?

**Comment by martndemus** [comment]
You can get the behavior you want by writing an `update` action that gets `id` from the passed in value and then sets that on the object.

**Comment by lcpriest** [comment]
Would the update not then be confused as the value is now the ID and not the object?
  
  
  

  
  
>

**Comment by lcpriest** [comment]
I've just used the default behaviour and store the object in the database, so I'm just curious.
  
  

  
  
>

**Comment by martndemus** [comment]
I opened https://github.com/DockYard/ember-one-way-controls/issues/109, closing this one.

**Comment by martndemus** [comment]
`2.0.0-alpha.5` contains an updated version of ember-one-way-controls. Your use case is now possible using the `optionTargetPath` property. [See the one-way-controls-docs](https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-select.md#working-with-objects-instead-of-strings).
