### ISSUE TITLE
Can you please open up the wiki?

### ISSUE THREAD

**Issue by lcpriest** [martndemus/ember-form-for#61]
I've been adding validations to my forms using https://github.com/DockYard/ember-validations.

It works really easily, just need to override one template file.

```
{{#if errors}}
  <div class={{joinedErrorClasses}}>
    {{#each errors as |error index|}}
      <div id={{concat errorId '-' index}} role="alert">{{error}}</div>
    {{/each}}
  </div>
{{/if}}
```

I think it would be a useful wiki file for someone in future.

**Comment by lcpriest** [comment]
Note, the difference is just to use {{error}} instead of {{error.message}}.

**Comment by martndemus** [comment]
@lcpriest #62 will fix this, by allowing either way.

**Comment by lcpriest** [comment]
Oh, perfect!
