### ISSUE TITLE
Select Form doesn't seem to select the Model's actual value by default

### ISSUE THREAD

**Issue by hhff** [martndemus/ember-form-for#66]
For a payload like:

```
// JSON
task: {
  id: 1,
  priority: "high"
}
```

model like
```
export default Model.extend({
  priority: attr('string'),

  possiblePriorities: [
    { label: 'Low', value: 'low' },
    { label: 'High', value: 'high' }
  ]
});
```

and a form like:
```
{{#form-for task as |f|}}
  {{!-- Selected Label is "Low" --}}
  {{f.select-field "priority" task.possiblePriorities optionValuePath="value" optionLabelPath="label"}}

  {{!-- Rendered Value is "high" --}}
  {{task.priority}}
{{/form-for}}
```

When rendered, the value in the select is "Low" (first value in possible priorities) rather than it's true value "High".

Am I missing something here?  Will update the README if so!

**Comment by martndemus** [comment]
@hhff `model.priority` should be `{ label: 'High', value: 'hight'}` and even be `===` to one of the objects in `possiblePriorities`.

**Comment by hhff** [comment]
oh the actual model value for `priority` should be an object?

**Comment by martndemus** [comment]
@hhff Not necessarily. Just the value supplied to the select-field should be equal to one of the options supplied for it to be seen as selected.

**Comment by martndemus** [comment]
See: #53 and https://github.com/DockYard/ember-one-way-controls/issues/109

**Comment by hhff** [comment]
nice!  TY!

**Comment by martndemus** [comment]
@hhff `2.0.0-alpha.5` contains an updated version of ember-one-way-controls. Your use case is now possible using the `optionTargetPath` property. [See the one-way-controls-docs](https://github.com/DockYard/ember-one-way-controls/blob/master/docs/one-way-select.md#working-with-objects-instead-of-strings).

**Comment by hhff** [comment]
perfect @martndemus thankyou!  I'll check this out soon.
