### ISSUE TITLE
"Embedded" form with relationships integration

### ISSUE THREAD

**Issue by jmschelcher** [martndemus/ember-form-for#68]
Hi,
thanks for your nice addon !
I would like to know if there is a convenient way to handle my models relationships with ember-form-for ?

Thanks,
Jean-Michel

**Comment by martndemus** [comment]
@jmschelcher I should totally add a `{{fieldset-for}}` component that does this.

**Comment by jmschelcher** [comment]
wow, you are already working on it ! :-)

**Comment by martndemus** [comment]
Closing because #69 merged. Released in 2.0.0-alpha.4

**Comment by jmschelcher** [comment]
many thanks for the modifications !
